plugins { id 'com.android.application' }
android {
    namespace 'br.com.cinemajunto'
    compileSdk 35
    defaultConfig {
        applicationId 'br.com.cinemajunto'
        minSdk 29
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        versionCode 4
        versionName '0.4-teste'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
